### ISSUE TITLE
TextExtractor fails for a large PDF file

### ISSUE THREAD

**Issue by zuphilip** [infolis/infoLink#31]
The executation `611ac540-8df0-11e5-bf13-db6946410e6b` with the pdf file http://infolis.gesis.org/infolink/api/infolisFile/3ff3d500-8df0-11e5-bf13-db6946410e6b gave some fatal errors:

```
    DEBUG [Wed Nov 18 13:27:45 CET 2015 -- TextExtractor] Start extracting from [FILE: mit-vielen-allbus.pdf (type: application/pdf)]
    FATAL [Wed Nov 18 13:27:45 CET 2015 -- TextExtractor] Error reading PDF from stream: java.io.IOException
    FATAL [Wed Nov 18 13:27:45 CET 2015 -- TextExtractor] Error opening input stream: java.io.IOException
    ERROR [Wed Nov 18 13:27:45 CET 2015 -- TextExtractor] Extraction caused exception in file [FILE: mit-vielen-allbus.pdf (type: application/pdf)]: java.io.IOException java.io.IOException at org.apache.pdfbox.filter.FlateFilter.decode(FlateFilter.java:109) at org.apache.pdfbox.cos.COSStream.doDecode(COSStream.java:379) at org.apache.pdfbox.cos.COSStream.doDecode(COSStream.java:291) at org.apache.pdfbox.cos.COSStream.getUnfilteredStream(COSStream.java:225) at org.apache.pdfbox.pdfparser.PDFStreamParser.<init>(PDFStreamParser.java:117) at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:251) at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:235) at org.apache.pdfbox.util.PDFStreamEngine.processStream(PDFStreamEngine.java:215) at org.apache.pdfbox.util.PDFTextStripper.processPage(PDFTextStripper.java:460) at org.apache.pdfbox.util.PDFTextStripper.processPages(PDFTextStripper.java:385) at org.apache.pdfbox.util.PDFTextStripper.writeText(PDFTextStripper.java:344) at org.apache.pdfbox.util.PDFTextStripper.getText(PDFTextStripper.java:275) at io.github.infolis.algorithm.TextExtractor.extractText(TextExtractor.java:138) at io.github.infolis.algorithm.TextExtractor.extract(TextExtractor.java:94) at io.github.infolis.algorithm.TextExtractor.execute(TextExtractor.java:180) at io.github.infolis.algorithm.BaseAlgorithm.run(BaseAlgorithm.java:176) at io.github.infolis.scheduler.ExecutionScheduler$1.run(ExecutionScheduler.java:57) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745) Caused by: java.util.zip.DataFormatException: incorrect header check at java.util.zip.Inflater.inflateBytes(Native Method) at java.util.zip.Inflater.inflate(Inflater.java:259) at java.util.zip.Inflater.inflate(Inflater.java:280) at org.apache.pdfbox.filter.FlateFilter.decompress(FlateFilter.java:128) at org.apache.pdfbox.filter.FlateFilter.decode(FlateFilter.java:101) ... 19 more
    DEBUG [Wed Nov 18 13:27:45 CET 2015 -- TextExtractor] No of OutputFiles of this execution: 1
```

**Comment by kba** [comment]
http://infolis.gesis.org/infolink/api/execution/611ac540-8df0-11e5-bf13-db6946410e6b

**Comment by bolandka** [comment]
Thanks for pointing this out. In fact, the log levels were set in an inappropriate way: there was no fatal error in the execution, instead pdfBox failed to convert the pdf. Another error was that the number of output files was set to 1 instead of 0. We fixed both issues, the log should not be as confusing anymore.
