### ISSUE TITLE
400 Bad Request for ApplyPatternAndResolve with DaraSolrQueryService 

### ISSUE THREAD

**Issue by Dommii** [infolis/infoLink#71]
```
{
  "algorithm": "io.github.infolis.algorithm.ApplyPatternAndResolve",
  "inputFiles": [
    "http://infolis.gesis.org/infolink/api/infolisFile/b3ce30f0-8f6d-11e5-8f69-051f8d3dc8ce"
  ],
  "patterns": [
    "http://infolis.gesis.org/infolink/api/infolisPattern/d2ec7fc0-8f48-11e5-9bfb-37e8acc5d407"
  ],
"queryServiceClasses": [
    "io.github.infolis.resolve.DaraSolrQueryService"
  ]
}
```

```
javax.ws.rs.BadRequestException: HTTP 400 Bad Request
        at io.github.infolis.datastore.CentralClient.put(CentralClient.java:133)
        at io.github.infolis.algorithm.BaseAlgorithm.persistExecution(BaseAlgorithm.java:158)
        at io.github.infolis.algorithm.BaseAlgorithm.run(BaseAlgorithm.java:193)
        at io.github.infolis.algorithm.ApplyPatternAndResolve.searchClassInRepositories(ApplyPatternAndResolve.java:120)
        at io.github.infolis.algorithm.ApplyPatternAndResolve.execute(ApplyPatternAndResolve.java:63)
        at io.github.infolis.algorithm.BaseAlgorithm.run(BaseAlgorithm.java:183)
        at io.github.infolis.scheduler.ExecutionScheduler$1.run(ExecutionScheduler.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Dommii** [comment]
line in code: getOutputDataStoreClient().put(Execution.class, getExecution());

**Comment by kba** [comment]
So around, 22:50? 22:45?

```
22:41:18.012 [ERROR] server.coffee: ERROR ...
```

In prettier JSON it's this:

```
stack: 
  """
    Error: request entity too large
      at readStream (/home/infolis-web/infolis-web/nod e_modules/body-parser/node_modules/raw-body/index.js:196:17)
      at getRawBody (/home/infolis-web/infolis-web/node_modules/body-parser/n ode_modules/raw-body/index.js:106:12)
      at read (/home/infolis-web/infolis-web/node_modules/body-parser/lib/read.js:76:3)
      at jsonPa rser (/home/infolis-web/infolis-web/node_modules/body-parser/lib/types/json.js:121:5)
      at Layer.handle [as handle_request] (/home/inf olis-web/infolis-web/node_modules/express/lib/router/layer.js:95:5)
      at trim_prefix (/home/infolis-web/infolis-web/node_modules/expre ss/lib/router/index.js:312:13)
      at /home/infolis-web/infolis-web/node_modules/express/lib/router/index.js:280:7
      at Function.proces s_params (/home/infolis-web/infolis-web/node_modules/express/lib/router/index.js:330:12)
      at next (/home/infolis-web/infolis-web/node _modules/express/lib/router/index.js:271:10)
      at expressInit (/home/infolis-web/infolis-web/node_modules/express/lib/middleware/init.  js:33:5)
      at Layer.handle [as handle_request] (/home/infolis-web/infolis-web/node_modules/express/lib/router/layer.js:95:5)
      at tri m_prefix (/home/infolis-web/infolis-web/node_modules/express/lib/router/index.js:312:13)
      at /home/infolis-web/infolis-web/node_modul es/express/lib/router/index.js:280:7
      at Function.process_params (/home/infolis-web/infolis-web/node_modules/express/lib/router/index .js:330:12)
      at next (/home/infolis-web/infolis-web/node_modules/express/lib/router/index.js:271:10)
      at query (/home/infolis-web/i nfolis-web/node_modules/express/lib/middleware/query.js:49:5)
      at Layer.handle [as handle_request] (/home/infolis-web/infolis-web/nod e_modules/express/lib/router/layer.js:95:5)
      at trim_prefix (/home/infolis-web/infolis-web/node_modules/express/lib/router/index.js:3 12:13)
      at /home/infolis-web/infolis-web/node_modules/express/lib/router/index.js:280:7
      at Function.process_params (/home/infolis- web/infolis-web/node_modules/express/lib/router/index.js:330:12)
      at next (/home/infolis-web/infolis-web/node_modules/express/lib/rou ter/index.js:271:10)
      at Function.handle (/home/infolis-web/infolis-web/node_modules/express/lib/router/index.js:176:3)
      at EventEm itter.handle (/home/infolis-web/infolis-web/node_modules/express/lib/application.js:173:10)
      at Server.app (/home/infolis-web/infolis -web/node_modules/express/lib/express.js:38:9)
      at Server.emit (events.js:110:17)
      at HTTPParser.parserOnIncoming [as onIncoming] ( _http_server.js:491:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
      at Socket.socketOnData (_http_server.js:34 3:22)
      at Socket.emit (events.js:107:17)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_read able.js:126:10)
      at TCP.onread (net.js:538:20)

  """
expected:   135732
length:     135732
limit:      102400
message:    request entity too larg e
status:     413
statusCode: 413
type:       entity.too.large
```

Apparently, there's a 10 MB limit for the ExpressJS body parser. Will increase that.

That must have been an aweful lot of logging in that exec.

**Comment by kba** [comment]
Correction: [`100 kB` is the default](https://github.com/expressjs/body-parser/blob/7847af6e5a36129eea0e0becfbcc521b839313ae/README.md#bodyparserrawoptions).
